#!/usr/bin/env python3
"""Generate the print edition's evidence appendix from appraisals/.

Appendix A is the apparatus readers pay for: every recommendation in
Delivering Better Oral Health with its strength label, the certainty its
own evidence statement claims, how many separate instructions it bundles,
and what it cites. It is generated rather than typed so it cannot drift
from the data behind it.

Appendix B indexes the search records.

Run via `make extract`, which runs extract_dboh.py first.
"""

from __future__ import annotations

import csv
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "appraisals" / "dboh-2025.csv"
SEARCHES = ROOT / "appraisals" / "searches"
APP = ROOT / "appendices"

GENERATED = (
    "<!-- GENERATED by scripts/make_appendices.py. Do not edit by hand. -->\n"
)

# Pandoc reads relative column widths off the dashes in the separator row,
# so these are load-bearing, not decoration.
W_MAIN = (
    "|:----|:----------------------------------------------"
    "|:--------------|-----:|:--------------|"
)
W_BUNDLED = (
    "|:----|-----:|:--------------"
    "|:-----------------------------------------------------------|"
)
W_SILENT = (
    "|:----|:--------------"
    "|:----------------------------------------------------------------|"
)

DOMAIN_ORDER = [
    "dental caries",
    "periodontal diseases",
    "oral cancer",
    "tooth wear",
]


def esc(s: str) -> str:
    """Make a cell safe inside a markdown pipe table.

    Also tidies the spacing artefacts left behind when <abbr> elements are
    unwrapped out of the guideline's HTML, which produce strings like
    "0.05% NaF ;" and "(2.26% NaF )".
    """
    # The CSV keeps a recommendation's bullets as " | ". Escaping that for a
    # pipe table renders a literal bar next to the bullet glyph, so turn the
    # separator into a middle dot and drop the now-redundant bullets.
    s = s.replace(" | \u2022 ", " \u00b7 ").replace(" | ", " \u00b7 ")
    s = s.replace("|", "\\|").replace("\n", " ")
    for bad, good in ((" ;", ";"), (" )", ")"), ("( ", "("), (" ,", ",")):
        s = s.replace(bad, good)
    return re.sub(r"\s{2,}", " ", s).strip()


def short(s: str, n: int) -> str:
    s = esc(s)
    return s if len(s) <= n else s[: n - 1].rstrip() + "\u2026"


def certainty_cell(row: dict) -> str:
    terms = row["certainty_terms"]
    if not terms:
        return "*none stated*"
    return esc(terms)


def build_evidence_appendix(rows: list[dict]) -> str:
    out = [
        GENERATED,
        "# Evidence tables {#sec-app-evidence}\n",
        textwrap.dedent(
            """
            Every recommendation in *Delivering Better Oral Health* as of the
            10 September 2025 edition, with the strength label from chapter 2
            and the certainty language from chapter 13.

            Two columns need a word of explanation.

            **Parts** is the number of separable instructions bundled into that
            one recommendation, counted from the guideline's own bullets. It is
            a floor, not a ceiling: a recommendation written as flowing prose
            can bundle just as much and counts as one here.

            **Certainty stated** lists every certainty term appearing in the
            recommendation's evidence statement, in the order they appear. Where
            more than one appears, they refer to different components, and the
            reader cannot tell from chapter 2 which of them the strength label
            was earned by. That is the subject of the chapter on bundling.

            Recommendations are given in shortened form so the tables fit the
            page. The full wording, the complete evidence statement and the
            guideline's own citations for every row are in
            `appraisals/dboh-2025.csv`, which also carries the reference list
            resolved from chapter 13's footnotes.

            Generated from `appraisals/dboh-2025.csv`. Crown copyright material,
            reproduced under the Open Government Licence v3.0.
            """
        ).strip()
        + "\n",
    ]

    for domain in DOMAIN_ORDER:
        drows = [r for r in rows if r["domain"] == domain]
        if not drows:
            continue
        out.append(f"\n## {domain.title()}\n")

        by_table: dict[str, list[dict]] = {}
        for r in drows:
            by_table.setdefault(r["ch2_table"], []).append(r)

        for table, trows in by_table.items():
            pop = trows[0]["population"]
            out.append(f"\n### Table {table}: {pop}\n")
            out.append("| ID | Recommendation | Strength | Parts | Certainty stated |")
            out.append(W_MAIN)
            for r in trows:
                out.append(
                    f"| {r['id'].replace('DBOH-', '')} "
                    f"| {short(r['recommendation'], 150)} "
                    f"| {esc(r['strength'])} "
                    f"| {r['n_components']} "
                    f"| {certainty_cell(r)} |"
                )
            out.append("")

    # --- the summary that carries the argument ------------------------
    strong = [r for r in rows if r["strength"] == "Strong"]
    bundled_strong = [r for r in strong if int(r["n_components"]) > 1]

    out.append("\n## Strong recommendations that bundle two or more instructions\n")
    out.append(
        "These are the rows where a single Strong label covers several separate\n"
        "instructions whose evidence differs. Ordered by how much they bundle.\n"
    )
    out.append("| ID | Parts | Certainty stated | Recommendation |")
    out.append(W_BUNDLED)
    for r in sorted(bundled_strong, key=lambda r: -int(r["n_components"])):
        out.append(
            f"| {r['id'].replace('DBOH-', '')} "
            f"| {r['n_components']} "
            f"| {certainty_cell(r)} "
            f"| {short(r['recommendation'], 180)} |"
        )

    # --- recommendations with no certainty stated ---------------------
    silent = [r for r in rows if not r["certainty_terms"] and r["strength"]]
    out.append("\n## Recommendations whose evidence statement names no certainty\n")
    out.append(
        f"{len(silent)} of {len(rows)} recommendations carry a strength label "
        "with no certainty\nlevel anywhere in their evidence statement. Most are "
        "Good practice points, for\nwhich that is correct and by design. The "
        "Strong and Conditional ones are listed\nfirst.\n"
    )
    out.append("| ID | Strength | Recommendation |")
    out.append(W_SILENT)
    order = {"Strong": 0, "Conditional": 1}
    for r in sorted(silent, key=lambda r: (order.get(r["strength"], 2), r["id"])):
        out.append(
            f"| {r['id'].replace('DBOH-', '')} "
            f"| {esc(r['strength'])} "
            f"| {short(r['recommendation'], 190)} |"
        )

    out.append("")
    return "\n".join(out)


def build_search_appendix() -> str:
    out = [
        GENERATED,
        "# Search strategies {#sec-app-searches}\n",
        textwrap.dedent(
            """
            Every search run for this book, with the query as submitted, the date
            it was run, how many records came back, and what was screened in.

            All searches were run in **PubMed only**, by one person. That is a
            real limitation and is stated here rather than buried: a full
            systematic search would add Embase, CENTRAL, CINAHL and the trial
            registries, and would have two people screening independently. Where
            a Cochrane review of a question already exists, this book leans on
            its search rather than pretending to substitute for it.

            A search that found nothing is recorded too. A null result is a
            finding, and an undocumented null result cannot be told apart from
            not having looked.
            """
        ).strip()
        + "\n",
    ]

    files = sorted(SEARCHES.glob("ch*.md")) if SEARCHES.exists() else []
    if not files:
        out.append("\n*No search records yet.*\n")
        return "\n".join(out)

    for f in files:
        text = f.read_text(encoding="utf-8")
        # Demote every heading one level so the chapter records nest under
        # this appendix's H1 instead of competing with it.
        lines = []
        for line in text.splitlines():
            if line.startswith("#"):
                line = "#" + line
            lines.append(line)
        out.append("\n" + "\n".join(lines).strip() + "\n")

    return "\n".join(out)


def main() -> int:
    if not DATA.exists():
        sys.exit(f"{DATA} not found. Run scripts/extract_dboh.py first.")

    rows = list(csv.DictReader(DATA.open(encoding="utf-8")))
    APP.mkdir(parents=True, exist_ok=True)

    (APP / "a-evidence-tables.qmd").write_text(build_evidence_appendix(rows))
    (APP / "b-search-strategies.qmd").write_text(build_search_appendix())

    n_search = len(list(SEARCHES.glob("ch*.md"))) if SEARCHES.exists() else 0
    print(
        f"appendices: A from {len(rows)} recommendations, "
        f"B from {n_search} search record(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
